### ISSUE TITLE
It's failed in XCode 6.3

### ISSUE THREAD

**Issue by AcmenDong** [omz/ColorSense-for-Xcode#55]

**Comment by ReyesMagos** [comment]
In XCode 6.2 UUID A16FF353-8441-459E-A50C-B071F53F51B7 should be added to DVTPlugInCompatibilityUUIDs array in Info.plist file of the project.

In XCode 6.3 UUID 9F75337B-21B4-4ADC-B558-F9CADF7073A7

Rewards

**Comment by becomedev** [comment]
many thanks to @ReyesMagos 
It's working now

**Comment by runia** [comment]
When will the update?

**Comment by becomedev** [comment]
@runia , the last commit solved this problem
so we should close this issue.
Thanks,

**Comment by AcmenDong** [comment]
now it can work,thanks

**Comment by AlexanderZubkov** [comment]
UUID for XCode 6.3.2 - E969541F-E6F9-4D25-8158-72DC3545A6C6

**Comment by marcoscurvello** [comment]
Thanks :+1:
