### ISSUE TITLE
not work in XCode 6.3.2

### ISSUE THREAD

**Issue by balkarov** [omz/ColorSense-for-Xcode#58]

**Comment by runia** [comment]
resolved problem i add in plist UUID - E969541F-E6F9-4D25-8158-72DC3545A6C6

**Comment by balkarov** [comment]
for ios 6.4:   7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90

**Comment by jonsnowwinterfell** [comment]
i have no idea how to do it,could u  make  a  screenshot in "info-plist"  thank  u very  much .

**Comment by DanClarke-io** [comment]
This should no longer be required @jonsnowwinterfell, as of cb56bab857731dd7653c1ac63eb8787769f2cf90 this will now run a script to get the correct UDID for the build.

Hopefully this can now be closed?

Hope this helps!
