### ISSUE TITLE
Not working on Xcode 7 beta

### ISSUE THREAD

**Issue by abutalha** [omz/ColorSense-for-Xcode#62]
Hi, can you please guide me to fix this beautiful plugin on Xcode 7? 
thank You

**Comment by ThePantsThief** [comment]
Bump. I even added the new key to `DVTPlugInCompatibilityUUIDs` but that didn't fix it.

**Comment by abutalha** [comment]
I was able to get it back in Xcode again! 
- No idea how it worked, but I just removed the old plugin, 
- Downloaded the source again and built
- Restarted the Xcode and it worked, boom! 

thank you.
