### ISSUE TITLE
Does not work on xcode 7

### ISSUE THREAD

**Issue by trialabc** [omz/ColorSense-for-Xcode#63]
I have not been able to run this wonderful plugin in xcode 7. It seems like one of the function is deprecated on the OSX 10.10.

The deprecated function is :  - (NSRect) firstRectForCharacterRange:(NSRange)theRange

Please help see if you can solve this problem. Thanks in advance!!  :smile:

**Comment by DanClarke-io** [comment]
Hi @trialabc, this version may not work, but the fork from [johnnywjy](https://github.com/johnnywjy/ColorSense-for-Xcode) compiles and works fine for me:
![Screenshot from Xcode](http://i.imgur.com/m2xRdI1.png)

You can find this fork here: https://github.com/johnnywjy/ColorSense-for-Xcode

Hope this helps!

**Comment by trialabc** [comment]
Thx a lot! It works okay although it still have that warning when compiling.
